"""
LLM-as-a-judge 评估思维链 (CoT) 质量脚本。

功能：
1. 读取包含 <sim_reasoning> 的数据文件。
2. 使用高智商模型 (Judge) 评估 CoT 是否为合格的“前向模拟”。
3. 重点检测是否犯了“事后诸葛亮” (Hindsight Bias) 的错误。
4. 输出格式为 JSONL，包含原始数据及 evaluation_result 和 evaluation_reasoning。

用法示例：
python evaluate_cot_quality.py \
  --input data_with_cot.jsonl \
  --output data_judged.jsonl \
  --model-config judge_models.yaml \
  --workers 8
"""

import argparse
import json
import os
import sys
import yaml
import re
import random
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any, Dict, List, Optional
from tqdm import tqdm
import litellm

# ===================== 1. Judge Prompt 设计 =====================

JUDGE_SYSTEM_PROMPT = """You are an expert code execution analyst and a strict evaluator of reasoning quality.
Your goal is to evaluate a "Chain of Thought" (CoT) trace generated by an AI simulator.

The AI simulator was tasked with predicting the execution result of a specific command on a codebase, **without knowing the result beforehand**.
You must determine if the CoT represents a valid, high-quality **forward simulation** or if it fails (e.g., hallucinates, lacks detail, or cheats by explaining the result post-hoc).

### Input Data Provided to You:
1. **Context Summary**: A brief summary of the code/patch being executed.
2. **Command**: The command that was simulated.
3. **True Execution Result**: The actual stdout/stderr/exit_code (Ground Truth).
4. **Generated CoT**: The simulation trace produced by the AI.

### Evaluation Criteria (Pass requirements):

1. **Forward Simulation (Crucial)**:
   - The CoT must read like a step-by-step trace of the code execution *before* the result is known.
   - It should say things like: "The code enters function X...", "The condition Y is True...", "Therefore, it raises an exception...".
   - **FAIL** if it exhibits Hindsight Bias: "The output shows an error, so...", "As we can see in the stdout...", "The test failed because...". The reasoning must NOT rely on observing the provided True Result.

2. **Logical Correctness**:
   - The reasoning must follow the logic of the code/patch provided.
   - The conclusion reached by the CoT (e.g., "It will crash with exit code 1") must match the **True Execution Result**.
   - If the CoT predicts success but the code actually failed, this is a **NO**.

3. **Detail & Consistency**:
   - The CoT should be detailed enough to explain *why* the result happened based on code logic.

### Output Format

You must output your reasoning followed by a final decision in a latex box.

Structure:
[Detailed analysis of whether the CoT meets the criteria, pointing out specific good or bad lines]

\boxed{Yes}  <-- If it meets ALL criteria.
\boxed{No}   <-- If it fails ANY criteria (wrong result, backward reasoning, cheating, poor quality).
"""

def extract_judge_label(content: str) -> str:
    if not content:
        return "Error"
    
    # 1. 修复：增加对退格符的容错（防止输入端未转义）
    # \x08 匹配 ASCII Backspace
    pattern_strict = r"(\\boxed|\x08oxed)\s*\{\s*(Yes|No)"
    match = re.search(pattern_strict, content, re.IGNORECASE | re.DOTALL)
    if match:
        return match.group(2).title() # 注意组号变为 2

    pattern_loose = r"(\[\[|\*\*|\[)\s*(Yes|No)\s*(\]\]|\*\*|\])"
    match_loose = re.search(pattern_loose, content, re.IGNORECASE)
    if match_loose:
        return match_loose.group(2).title()

    tail = content[-200:]
    yes_matches = list(re.finditer(r"\bYes\b", tail, re.IGNORECASE))
    no_matches = list(re.finditer(r"\bNo\b", tail, re.IGNORECASE))

    # 2. 修复：兜底逻辑比较最后出现的位置，而不是仅仅看是否存在
    last_yes_pos = yes_matches[-1].start() if yes_matches else -1
    last_no_pos = no_matches[-1].start() if no_matches else -1

    if last_yes_pos > last_no_pos:
        return "Yes"
    elif last_no_pos > last_yes_pos:
        return "No"
    
    return "Error"
    

def build_judge_prompt(example: Dict[str, Any]) -> str:
    """
    构建发送给 Judge 模型的 User Prompt。
    """
    # 提取必要的上下文
    ctx = example.get("context", {}) or {}
    problem = ctx.get("problem_statement", "N/A")
    patch = ctx.get("agent_patch", "N/A")
    command = ctx.get("command_to_simulate", "N/A")
    
    # 真实结果
    real_stdout = example.get("real_stdout", "")
    real_stderr = example.get("real_stderr", "")
    real_exit_code = example.get("real_error_code", 0)
    
    # 待评估的 CoT
    cot_content = example.get("cot_completion", "")
    
    # 简单截断过长的输出以节省 token（保留关键信息即可）
    if len(str(real_stdout)) > 2000:
        real_stdout = str(real_stdout)[:1000] + "\n...[Truncated]...\n" + str(real_stdout)[-1000:]
    
    return f"""
Please evaluate the following simulation CoT.

### 1. Context Summary
**Problem:** {problem[:500]}...
**Agent Patch:** 
```diff
{patch}
```
**Command:** `{command}`

### 2. True Execution Result (Ground Truth)
Exit Code: {real_exit_code}
Stdout:
{real_stdout}
Stderr:
{real_stderr}

### 3. Generated CoT (To Evaluate)
<sim_reasoning>
{cot_content}
</sim_reasoning>

### Your Judgment
Is this CoT a valid, correct, **forward-looking** simulation that matches the ground truth?
Remember: If the CoT analyzes the "True Execution Result" (e.g., "I see the error is...") instead of predicting it from code, you must answer \boxed{{No}}.
"""

# ===================== 2. 核心处理逻辑 =====================

def evaluate_single_sample(
    example: Dict[str, Any],
    model_config_list: List[Dict[str, str]],
    temperature: float = 0.0,
    max_tokens: int = 1024
) -> Dict[str, Any]:
    """
    对单个样本进行评估
    """
    # 如果生成的 CoT 本身为空，直接判负
    if not example.get("cot_completion"):
        result = dict(example)
        result["judge_reasoning"] = "No CoT generated."
        result["judge_label"] = "No"
        return result

    user_prompt = build_judge_prompt(example)
    
    messages = [
        {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
        {"role": "user", "content": user_prompt},
    ]

    # 随机选择一个 Judge 模型配置（负载均衡）
    config = random.choice(model_config_list)
    model_name = config["model_name"]
    base_url = config.get("base_url")
    api_key = config.get("api_key")
    
    # LiteLLM 模型名称处理
    litellm_model = model_name if "openai/" in model_name or "claude" in model_name else f"openai/{model_name}"

    try:
        response = litellm.completion(
            model=litellm_model,
            messages=messages,
            api_base=base_url,
            api_key=api_key,
            temperature=temperature,
            max_tokens=max_tokens,
            timeout=120  # Judge 通常比较快
        )
        content = response.choices[0].message.content
        
        # === 修改开始: 使用增强的提取逻辑 ===
        label = extract_judge_label(content)
        # === 修改结束 ===

        out = dict(example)
        out["judge_reasoning"] = content
        out["judge_label"] = label
        out["judge_model"] = model_name
        return out

    except Exception as e:
        print(f"[Judge Error] {model_name} failed: {e}")
        out = dict(example)
        out["judge_reasoning"] = f"Judge execution failed: {str(e)}"
        out["judge_label"] = "Error"
        return out

def process_wrapper(args_tuple):
    return evaluate_single_sample(*args_tuple)

# ===================== 3. 主程序 =====================

def main():
    parser = argparse.ArgumentParser(description="Evaluate CoT traces using LLM-as-a-judge.")
    parser.add_argument("--input", required=True, help="Path to JSONL file containing 'cot_completion'")
    parser.add_argument("--output", required=True, help="Path to save evaluated JSONL")
    parser.add_argument("--model-config", required=True, help="Path to Judge model config YAML")
    parser.add_argument("--workers", type=int, default=8, help="Number of parallel workers")
    args = parser.parse_args()

    # 1. 加载模型配置
    with open(args.model_config, 'r', encoding='utf-8') as f:
        config_data = yaml.safe_load(f)
        models = config_data.get('models', [])
        if not models:
            print("Error: No models found in config.")
            sys.exit(1)

    # 2. 读取数据
    data = []
    with open(args.input, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                data.append(json.loads(line))
    
    # data = data[:10]
    print(f"Loaded {len(data)} samples for evaluation.")

    # 3. 准备并行任务
    tasks = []
    for item in data:
        tasks.append((item, models, 0.7, 32768)) # item, models, temp, max_tokens

    results = []
    
    # 4. 执行评测
    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        # 提交任务
        future_to_item = {executor.submit(process_wrapper, t): t[0] for t in tasks}
        
        with open(args.output, "w", encoding="utf-8") as f_out:
            for future in tqdm(as_completed(future_to_item), total=len(tasks), desc="Judging"):
                try:
                    res = future.result()
                    results.append(res)
                    # 实时写入
                    f_out.write(json.dumps(res, ensure_ascii=False) + "\n")
                    f_out.flush()
                except Exception as e:
                    print(f"Critical error in worker: {e}")

    # 5. 统计结果
    yes_count = sum(1 for r in results if r.get("judge_label") == "Yes")
    no_count = sum(1 for r in results if r.get("judge_label") == "No")
    error_count = sum(1 for r in results if r.get("judge_label") not in ["Yes", "No"])

    print("\n=== Evaluation Summary ===")
    print(f"Total: {len(results)}")
    print(f"Pass (Yes): {yes_count} ({yes_count/len(results)*100:.2f}%)")
    print(f"Fail (No) : {no_count} ({no_count/len(results)*100:.2f}%)")
    print(f"Errors    : {error_count}")
    print(f"Results saved to {args.output}")

if __name__ == "__main__":
    main()